[package]
name = "axum-myroutes-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true

[lib]
proc-macro = true

[features]
nightly = []

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", default-features = false, features = ["extra-traits", "full", "parsing", "printing", "proc-macro"] }

[lints]
workspace = true
